# Generated by Django 4.1.4 on 2023-01-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="SOME STRING", max_length=200)),
                ("Type", models.CharField(default="SOME STRING", max_length=200)),
                ("Currency", models.CharField(default="Rupee", max_length=200)),
                ("Country", models.CharField(default="India", max_length=200)),
                ("State", models.CharField(default="Tamil Nadu", max_length=200)),
                ("Location", models.CharField(default="xxxx", max_length=200)),
            ],
        ),
    ]
