# Generated by Django 4.1.4 on 2023-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockandpurchase", "0002_alter_items_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
