# Generated by Django 4.1.4 on 2023-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Items", models.CharField(default=None, max_length=32)),
                ("Price", models.IntegerField()),
            ],
        ),
    ]
