# Generated by Django 4.1.4 on 2023-04-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashboard_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="Items",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="Count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="Price",
            field=models.IntegerField(default=0),
        ),
    ]
