# Generated by Django 4.1.4 on 2022-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=200)),
                ("LastName", models.CharField(max_length=200)),
                ("DOB", models.CharField(max_length=200)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone_Number", models.IntegerField()),
                ("Password", models.CharField(max_length=8)),
                ("ConformPassword", models.CharField(max_length=8)),
            ],
        ),
    ]
