# Generated by Django 4.1.4 on 2022-12-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_rename_lastname_registration_lastname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="DOB",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="Lastname",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="Password",
        ),
    ]
