# Generated by Django 4.1.4 on 2023-01-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_remove_registration_dob_remove_registration_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="Email",
            field=models.EmailField(default="SOME STRING", max_length=254),
        ),
        migrations.AddField(
            model_name="registration",
            name="Lastname",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="registration",
            name="Password",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="registration",
            name="Phone_Number",
            field=models.IntegerField(default=12221111221),
        ),
        migrations.AlterField(
            model_name="registration",
            name="Firstname",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
    ]
