# Generated by Django 4.1.4 on 2023-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_registration_dob"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="SOME STRING", max_length=200)),
                ("EmailID", models.EmailField(default="No EmailID", max_length=254)),
                ("Level", models.CharField(default="Labour", max_length=200)),
                ("Phone_Number", models.IntegerField(default=0)),
                ("Attendance", models.IntegerField(default=100)),
            ],
        ),
    ]
